service: bespokeDB

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:*
        Resource:
          - arn:aws:dynamodb:us-east-1:063686265830:table/contacts


functions:
  ping:
    handler: src/test.ping
    events:
      - http:
          path: /ping
          method: get
  addContact:
    handler: src/contacts/add.addContact
    events:
      - http:
          path: /contact
          method: post
  getContacts:
    handler: src/contacts/get.getContacts
    events:
      - http:
          path: /contact
          method: get

resources:
  Resources:
    ContactsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: contacts
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH